### ISSUE TITLE
Zen Coding not working with cshtml and razor files

### ISSUE THREAD

**Issue by MarkLFT** [madskristensen/ZenCodingVS#14]
### Installed product versions
- VS2019 Professional
- This extension: 1.2.12

### Description
When using a cshtml or razor file TAB Expansion does not work.

### Steps to recreate
Create either a cshtml or razor file.
Create some standard HTML markup
Enter any standard appreviation  i.e div.row then press tab.

### Current behavior
The cursor just tabs across the page

### Expected behavior
Expand text as in a regular html page.

**Comment by TheBinaryGuy** [comment]
I'm having the same issue as well. Any luck yet?

**Comment by Hrolgar** [comment]
Is there any fix for this yet? I've had to go from VSCode to VS19 for work purposes. Hard to live without emmet. This extension seems like it would do the trick for me.

**Comment by TheBinaryGuy** [comment]
@Hrolgar Yes actually. In my case it was the experimental Razor editor that was causing the problem, so if you have that on, try turning it off, restart VS and see if that fixes it.

![image](https://user-images.githubusercontent.com/13674136/102128202-8648a100-3e73-11eb-81c8-0d4d610a20e0.png)

**Comment by Hrolgar** [comment]
@TheBinaryGuy  that did the trick!
I can't tell you how happy I am now! Cheers man!

**Comment by TheBinaryGuy** [comment]
@Hrolgar No worries man, glad it helped. 👍

**Comment by dealdiane** [comment]
Works for me as well. What features are we missing by turning that experimental editor off?

**Comment by TheBinaryGuy** [comment]
@dealdiane I haven't looked into the new editor as much, I only occasionally use Razor nowadays. But here's a blog post from Microsoft if you want to read more about it: https://devblogs.microsoft.com/aspnet/improvements-to-the-new-razor-editor-in-visual-studio/

**Comment by johandanforth** [comment]
Also not working in VS2022 (Preview 7.0), even if the language server option is enabled. Seems to work for pure html files sometimes, but also krasches VS totally sometimes.

**Comment by madskristensen** [comment]
@johandanforth what file extension do you expect it to work on that it doesn't?

**Comment by johandanforth** [comment]
Hej Mads. I tried it on a .cshtml file in the ~/Views/Home/ directory of a vanilla .net 6 MVC project. Nothing happens. Also tried "tabbing" inside and outside div elements. Nothing.

Then I created a new .html file, and there it worked. I tried to enable the experimental setting for html/css language service, but there was no change. But after enabling that option, VS2022 froze and crashed when I tried a simple "div-tab" in the html-file. Actually something is not fully alright with the extension, Vs freeze/die/restart a couple of times now that I try it some more. 
![Skärmbild 2021-11-05 225409](https://user-images.githubusercontent.com/527037/140583157-764e46f9-4740-49d8-af8b-f485bc9b2ccf.png)

**Comment by johandanforth** [comment]
@madskristensen I got a little longer. I went into tools->options->text editor->Html->Advanced and selected to "Use legacy Razor editor for ASP.NET Core" and restarted. Now ZenCoding kicks in, expands a simple "div" or whatever, but then it crashes, every time (se uploaded images). When using the "new" razor editor (whatever that is), it seems it is of another ContentType than "HTMLX", right? I don't know anything about these things really, but to create a IVsTextViewCreationListener you have to specify the ContenType for the specific kind of "page editor" with something like:

`   
    [Export(typeof(IVsTextViewCreationListener))]
    [ContentType("HTML")]
    [ContentType("HTMLX")]
    [TextViewRole(PredefinedTextViewRoles.Document)]
    public class CommandRegistration : IVsTextViewCreationListener 
    { ... and so on
`
but the ExpandCommand in ZenCodingVS is never executing for razor pages in ASP.NET Core in VS2022. 

![zencoding3 - options](https://user-images.githubusercontent.com/527037/140587549-d62d012e-1f9c-4d21-ad3d-f76022100e70.png)
.
![zencoding1](https://user-images.githubusercontent.com/527037/140587555-b2827557-87bf-49cb-a549-4e637885e79d.png)
![zencoding2](https://user-images.githubusercontent.com/527037/140587558-9decd675-90f9-4dc1-90bb-d90ab5f3ea68.png)

**Comment by johandanforth** [comment]
Adding the "RAZOR" content type to the `CommandRegistration` class got ZenCoding working, but it crashes and restarts eventually for no reason. Guess one have to look at activity logs or such, which I'm not familiar with.
```csharp
namespace ZenCodingVS
{
    [Export(typeof(IVsTextViewCreationListener))]
    [ContentType("HTML")]
    [ContentType("HTMLX")]
    [ContentType("RAZOR")]
    [TextViewRole(PredefinedTextViewRoles.Document)]
    public class CommandRegistration : IVsTextViewCreationListener
    {
        [Import]
        public IVsEditorAdaptersFactoryService EditorAdaptersFactoryService { get; set; }
```

**Comment by johandanforth** [comment]
I ran devenv.exe with logging, and got an activity log for you @madskristensen if it may help you.
[activitylog.zip](https://github.com/madskristensen/ZenCodingVS/files/7490979/activitylog.zip)
