### ISSUE TITLE
Latest update causing VS crashes when attempting to use ZenCoding

### ISSUE THREAD

**Issue by codywilliamson** [madskristensen/ZenCodingVS#19]
### Installed product versions
- Visual Studio: 2019 Enterprise
- This extension: 1.2.15

### Description
In a CSHTML file, every time I try to use auto-completion, my visual studio crashes. This did not happen until the most recent update.

### Steps to recreate
1. Create a CSHTML file 
2. Try to use ZenCoding
3. Crash

### Current behavior
I should be able to, for example, type ".testDiv" and hit Tab, then ".testDiv" should expand to `<div class="testDiv"></div>` However, when I type ".testDiv" then hit Tab, my visual studio crashes.

### Expected behavior
I should be able to, for example, type ".testDiv" and hit Tab, then ".testDiv" should expand to `<div class="testDiv"></div>`.

**Comment by madskristensen** [comment]
I've uploaded version 1.2.17 which will hopefully fix the issue

**Comment by stamminator** [comment]
I was having the same issue with vbhtml and have confirmed that the issue is no longer taking place with 1.2.17. Thanks for the quick resolution, Mads!

**Comment by codywilliamson** [comment]
I know its late, but you fixed this quite immediately and I was so appreciative as I use it daily like many, I'm sure. Thanks for the quick resolution, and Happy New Year!
